<?php

namespace BlueSpice\DistributionConnector\Maintenance\PostDatabaseUpdate;

use CommentStoreComment;
use LoggedUpdateMaintenance;
use MediaWiki\Revision\RevisionRecord;
use MediaWiki\Revision\SlotRecord;
use Title;
use User;
use WikiPage;

class AddTemplateUserPageStandardContent extends LoggedUpdateMaintenance {

	/**
	 * @inheritDoc
	 */
	protected function doDBUpdates() {
		$title = Title::makeTitle( NS_TEMPLATE, 'User' );
		$this->output( "Creating page '{$title->getPrefixedDBkey()}'..." );
		$wikipage = WikiPage::factory( $title );
		$updater = $wikipage->newPageUpdater( User::newSystemUser( 'BSMaintenance' ) );
		$content = $wikipage->getContentHandler()->makeContent( '', $title );
		$updater->setContent( SlotRecord::MAIN, $content );
		$comment = CommentStoreComment::newUnsavedComment( 'Autogenerated' );
		$newRevision = $updater->saveRevision( $comment );
		if ( $newRevision instanceof RevisionRecord ) {
			$this->output( "done.\n" );
		} else {
			$this->output( "error.\n" );
		}

		return true;
	}

	/**
	 * @inheritDoc
	 */
	protected function getUpdateKey() {
		return 'bs-cloudclient-add-template-userpage-standard-content';
	}
}
